#ifndef MCML_CONFIG
#define MCML_CONFIG

// #define MCML_CPU_SINGLE_THREAD
#define MCML_CPU_MULTIPLE_THREADS
// #define MCML_GPU_UHD_MULTIPLE_THREADS
// #define MCML_GPU_MULTIPLE_THREADS

#ifdef MCML_CPU_SINGLE_THREAD
constexpr size_t LAYER_OUTPUT_SIZE_X = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 16;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;
constexpr size_t SIMULATION_REPEATS_COUNT = 1024 * 256 * 256 / 6;

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 1;
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 1;

// #define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
#define FEATURE_ALIGNED_DEVICE_ALLOC
#endif

#ifdef MCML_CPU_MULTIPLE_THREADS
constexpr size_t LAYER_OUTPUT_SIZE_X = 128;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 128;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 128;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 1;
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 16;

constexpr size_t SIMULATION_REPEATS_COUNT = 1'000'000 / CONFIGURATION_WORK_GROUP_SIZE / CONFIGURATION_WORK_GROUP_THREADS_COUNT;

// #define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
#define FEATURE_ALIGNED_DEVICE_ALLOC
#endif

#ifdef MCML_GPU_UHD_MULTIPLE_THREADS
constexpr size_t LAYER_OUTPUT_SIZE_X = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 16;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;
constexpr size_t SIMULATION_REPEATS_COUNT = 1024 / 6 * 32;

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 256 / 32;
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 256;

#define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
#define FEATURE_ALIGNED_DEVICE_ALLOC
#endif

#ifdef MCML_GPU_MULTIPLE_THREADS
constexpr size_t LAYER_OUTPUT_SIZE_X = 32;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 32;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 32;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;
constexpr size_t SIMULATION_REPEATS_COUNT = 37*10; // 37

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 31; // 31
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 88000; // 88000

#define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
#define FEATURE_ALIGNED_DEVICE_ALLOC
#endif



#endif