#ifndef MCML_CONFIG
#define MCML_CONFIG

using data_type_t = float;
namespace libset = sycl;

#define OPT_RAND
#define OPT_MTX

// #define MCML_CPU_SINGLE_THREAD
// #define MCML_CPU_MULTIPLE_THREADS
// #define MCML_GPU_UHD_MULTIPLE_THREADS
#define MCML_GPU_MULTIPLE_THREADS

#ifdef MCML_CPU_SINGLE_THREAD
constexpr size_t LAYER_OUTPUT_SIZE_X = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 16;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 1;
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 1;

constexpr size_t SIMULATION_REPEATS_COUNT = 1'000'000 / CONFIGURATION_WORK_GROUP_SIZE / CONFIGURATION_WORK_GROUP_THREADS_COUNT;

// #define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
#define FEATURE_ALIGNED_DEVICE_ALLOC
#endif

#ifdef MCML_CPU_MULTIPLE_THREADS
constexpr size_t LAYER_OUTPUT_SIZE_X = 128;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 128;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 128;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 32;
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 16;

constexpr size_t SIMULATION_REPEATS_COUNT = 100'000'000 / CONFIGURATION_WORK_GROUP_SIZE / CONFIGURATION_WORK_GROUP_THREADS_COUNT;

// #define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
#define FEATURE_ALIGNED_DEVICE_ALLOC
#endif

#ifdef MCML_GPU_UHD_MULTIPLE_THREADS
constexpr size_t LAYER_OUTPUT_SIZE_X = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 16;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 256 / 32;
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 256;

constexpr size_t SIMULATION_REPEATS_COUNT = 100'000 / CONFIGURATION_WORK_GROUP_SIZE / CONFIGURATION_WORK_GROUP_THREADS_COUNT;

#define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
#define FEATURE_ALIGNED_DEVICE_ALLOC
#endif

#ifdef MCML_GPU_MULTIPLE_THREADS
constexpr size_t LAYER_OUTPUT_SIZE_X = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Y = 16;
constexpr size_t LAYER_OUTPUT_SIZE_Z = 16;
constexpr size_t LAYER_OUTPUT_COUNT = 1;

constexpr size_t SIMULATION_RANDOM_SEED = 42;
constexpr size_t SIMULATION_LAYERS_COUNT = 24;

constexpr size_t CONFIGURATION_WORK_GROUP_THREADS_COUNT = 31; // 31
constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 88000; // for 10^7 +
// constexpr size_t CONFIGURATION_WORK_GROUP_SIZE = 8800; // for 10^5


constexpr size_t SIMULATION_REPEATS_COUNT = std::max<int>(1, 100'000'000 / CONFIGURATION_WORK_GROUP_SIZE / CONFIGURATION_WORK_GROUP_THREADS_COUNT);

// #define FEATURE_USE_GROUP_SUMMATOR
// #define FEATURE_USE_LOCAL_MEMORY
// #define FEATURE_USE_ATOMIC_SUMMATOR
// #define FEATURE_ALIGNED_DEVICE_ALLOC
#endif



#endif